Change clients to have a login bash as entrypoint
rucio/containers pull request #285
Opened 2024-01-17 11:18 UTC by maxnoe

This makes it possible to directly run a command in the docker image like this:

```
docker run [...] -v rucio-clients rucio download test:test.dat
```

`-l` is necessary to have bash load the startup script in `/etc/profile.d/` which sets up the rucio config.

Alternatively, that code could also be integrated into the entry point.

2024-02-06 16:43 UTC, maxnoe commented
@bari12 @rcarpa could you have a look? I am happy to adapt if you want something differently

2024-02-16 14:13 UTC, maany requested changes
LGTM! The existing instructions https://github.com/rucio/containers/blob/master/clients/README.md are still valid.

Additionally, users can directly execute single commands in the rucio-client container,
```
docker exec -it rucio-client rucio whoami
```
@maxnoe Could you update the README.md to indicate this?

2024-02-16 14:24 UTC, maxnoe commented
@maany That should be `docker run`, right? `exec` requires an existing container

2024-02-16 14:48 UTC, maany approved these changes
Looks good 👍

2024-02-16 14:55 UTC, bari12 commented
Awesome, thanks a lot!

2024-02-16 14:55 UTC, merged